---
title: "IYS2019_Juday_Changelog"
author: "Tim van der Stap"
date: "1/16/2021"
output: html_document
---

This file contains all the steps taken during the data processing from the raw or summarized data to the working file, for the Juday data collected during the 2019 IYS High Seas Expedition. 

***

Juday Summarized Data 2019:
- In column U (Date), the dates were initially as day,month,year (in that format). I have separated this column and created three new columns `day`, `month`, `year`, as these can be columns under the Darwin Core format also. I've removed the column `Date` as I will recreate this new using those three columns. The format of dates in Excel sometimes is read wrong within R and this simplified it. 

- row 2 [currently blank] is removed from the working file. 

- And additional tab is added to the Working File (`Species_corrected`) that show the changes made to species' scientific names to ensure that these taxa can be found in the WoRMS database (eg. Beroe sp. cannot be found but Beroe can). Some minor spelling errors were corrected. For all scientific names, the corrected names have been verified by [Evgeny?].

- in column D (Day/Night), I've replaced the Russian symbols with either day or night, where д = d (day), and н = n (night).

- In the size_mm column, some values showed up as larger numerical values in the eMOF. Consequently, I have added decimal points to reflect the integers. Specifically, the following changes were made:
* 0,8-1 --> 0,8-1,0
* 0,5-1 --> 0,5-1,0
* 0,4-1 --> 0,4-1,0
* 1,6-2 --> 1,6-2,0
* 2,1-4 --> 2,1-4,0
* 2-3 --> 2,0-3,0
* 5-8 --> 5,0-8,0
* 5-10 --> 5,0-10,0
* 4-5 --> 4,0-5,0
* 6-10 --> 6,0-10,0
* 5-6 --> 5,0-6,0
* 4,-4,5 --> 4,0-4,5
