---
title: "2020 IYS POM"
author: "Tim van der Stap"
date: "12/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
library(tidyverse)
library(lubridate)
library(obistools)
library(readxl)
library(parsedate)
library(googledrive)
library(here)
```

Out of curiosity, I just want to confirm that the metadata on date/time for HPLC, POM, Nutrients, CTD and phytoplankton all matches. First, we need to download the file, and read in the different sheets that are specific to each discipline: 

``` {r, eval = FALSE}

drive_download("https://docs.google.com/spreadsheets/d/1w7kXZvU7OpmJjBTKAMPGhJblfcF8cN74/edit#gid=989173203",
               path = here("Oceanography", "POM", "Metadata.xlsx"))

POM <- read_excel(here("Oceanography", "POM", "Metadata.xlsx"), sheet = "POM samples") %>% 
  mutate(Time = format(Time, "%H:%M:%S"),
         eventDate = format_iso_8601(as.POSIXct(paste(Date, Time),
                                                format = "%Y-%m-%d %H:%M:%S",
                                                tz = "Asia/Kamchatka")),
         eventDate = str_replace(eventDate, "\\+00:00", "Z"),
         cruise = "GoA2020",
         station = paste(cruise, Station, sep = "_Stn:"),
         cast = paste(station, "cast1", sep = ":"),
         ndepth = paste(cast, `Sample depth_m`, sep = ":niskin:"),
         sample = paste(ndepth, `Sample ID`, sep = ":"))
```

## Event Core

``` {r, eval = FALSE}

pom2020_cruise <- POM %>%
  select(eventID = cruise) %>%
  distinct(eventID) %>%
  mutate(eventRemarks = "cruise")

pom2020_station <- POM %>%
  select(eventID = station,
         parentEventID = cruise) %>%
  distinct(eventID, .keep_all = TRUE) %>%
  mutate(eventRemarks = "station")

pom2020_cast <- POM %>%
  select(eventID = cast,
         parentEventID = station,
         eventDate,
         decimalLatitude = Latitude,
         decimalLongitude = Longitude) %>%
  mutate(decimalLongitude = as.numeric(decimalLongitude),
         decimalLatitude = as.numeric(decimalLatitude)) %>%
  distinct(eventID, .keep_all = TRUE) %>%
  mutate(footprintWKT = paste("POINT", " (", pom2020_cast$decimalLongitude,
                              " ", pom2020_cast$decimalLatitude, ")"),
         eventRemarks = "cast")

coordinates <- obistools::calculate_centroid(pom2020_cast$footprintWKT) %>% select(coordinateUncertaintyInMeters)
pom2020_cast <- cbind(pom2020_cast, coordinates)

pom2020_depth <- POM %>%
  select(eventID = ndepth,
         parentEventID = ndepth,
         minimumDepthInMetres = `Sample depth_m`,
         maximumDepthInMetres = `Sample depth_m`) %>%
  distinct(eventID, .keep_all = TRUE) %>%
  mutate(eventRemarks = "sample")

pom2020_sample <- POM %>%
  select(eventID = sample,
         parentEventID = ndepth,
         samplingEffort = `Volume filtered_mL`) %>%
  distinct(eventID, .keep_all = TRUE) %>%
  mutate(eventRemarks = "subsample")

pom2020_event <- bind_rows(pom2020_cruise, pom2020_station, pom2020_cast, pom2020_depth, pom2020_sample) %>%
  select(eventID, parentEventID:maximumDepthInMetres, coordinateUncertaintyInMeters, eventRemarks) %>%
  mutate(type = "Event", 
         geodeticDatum = "EPSG:4326 WGS84")

obistools::check_eventids(pom2020_event)

write_csv(pom2020_event, here("Oceanography", "POM", "tidy_data", "pom2020_event.csv"))
```

















