---
title: "ChangeLog - Bongo"
author: "Tim van der Stap"
date: "8/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CHANGELOG

This document lists all of the data tidying and transformations applied to the raw file `Zoop Bongo Isotopes_IYS_Dry Weight_Mar31.xlsx`. 

Manual changes are described here, any scripts used to aid in data tidying can be found in `data_wrangle_bongo.Rmd`.

* For sampleID `Z383` the value in the `tissue` column has been changed to `whole` (as per pers. comm. with Brian H.)
* For sampleID `SS106` the value in the `lifeStage` column has been changed from `CV` to `adult` (as per comm. with Natalie Mahara). `CV` describes a life stage of copepodites, and SS106 is not a copepoda but E. pacifica.
* For sampleID `SS107` the value in the `lifeStage` column has been changed from `CV` to `NA`. This sample refers to Radiolarians, and the `CV` life stage is only applicable to copepodites. 

**Important data limitation alert**

Some samples were taken from Net 1 (abundance and community composition study) and also used in the fatty acid / isotope analysis. However, while that dataframe _usually_ does identify whether the samples were taken from Net 1, the datasheet from the abundance / community composition study does _not_ indicate which samples were also used for the other study. Given that the information on life stage and sex does not always match, it's not possible to accurately cross-reference. As such, dry weight and length measurements from samples taken from Net 1 are _not_ included in the extended measurementOrFact extension (eMOF). This omittance has no implications for the occurrence records (presence/absence) of all zooplankton collected with a bongo net. 